import Head from 'next/head'
import styled from 'styled-components';
import Dashboard from '../components/dashboard';
import Map from '../components/map';

interface HomeProps {
  GOOGLE_MAPS_API_KEY: string,
  vendors: any
}

const MainStyled = styled.main`
  display: flex;
`;

export default function Home({ GOOGLE_MAPS_API_KEY, vendors }: HomeProps) {
  return (
    <>
      <Head>
        <title>Vendors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyled>
        <Dashboard vendors={vendors} />
        <Map GOOGLE_MAPS_API_KEY={GOOGLE_MAPS_API_KEY}/>
      </MainStyled>
    </>
  )
}

const getVendors = async () => {
  const url = process.env.VENDORS_API_URL;

  if (url) {
    const res = await fetch(url);
    // The return value is *not* serialized
    // You can return Date, Map, Set, etc.
  
    // Recommendation: handle errors
    if (!res.ok) {
      // This will activate the closest `error.js` Error Boundary
      throw new Error('Failed to fetch data');
    }

    return res.json();
  }

  throw new Error('No vendors api url available');
}



export async function getStaticProps() {
  const GOOGLE_MAPS_API_KEY = process.env.GOOGLE_MAPS_API_KEY ?? '';
  const vendors = await getVendors();

  return { 
    props: {
      GOOGLE_MAPS_API_KEY,
      vendors
    }
  }
}