import Head from 'next/head'
import styled from 'styled-components';
import Dashboard from '../components/dashboard';
import Map from '../components/map';

interface HomeProps {
  GOOGLE_MAPS_API_KEY: string
}

const MainStyled = styled.main`
  display: flex;
`;

export default function Home({ GOOGLE_MAPS_API_KEY }: HomeProps) {
  return (
    <>
      <Head>
        <title>Vendors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainStyled>
        <Dashboard />
        <Map GOOGLE_MAPS_API_KEY={GOOGLE_MAPS_API_KEY}/>
      </MainStyled>
    </>
  )
}

export async function getStaticProps() {
  const GOOGLE_MAPS_API_KEY = process.env.GOOGLE_MAPS_API_KEY ?? '';

  return { 
    props: {
      GOOGLE_MAPS_API_KEY
    }
  }
}